### ISSUE TITLE
How to get tile by X and Y?

### ISSUE THREAD

**Issue by prsolucoes** [salviati/go-tmx#2]
How to get tile by X and Y?

My layer 0 contains my game meta data, all sprites in this layer will block movement.

```golang
log.Print(maps[p.Map].Layers[0])
```

But how i can do it? Can i get by X and Y?

**Comment by salviati** [comment]
Check out the [example](https://github.com/salviati/go-tmx/blob/master/tmx/example/tmx2console/console.go#L107).
